### ISSUE TITLE
transfer_sui fails with "int object has no attribute 'enum_name'" in 0.75.0 (worked in 0.72.0)

### ISSUE THREAD

**Issue by trenchawr** [FrankC01/pysui#261]
**What happened:**  
When invoking the `transfer_sui` method using an `int` for the `amount` parameter on **pysui** `0.75.0`, the call fails with:

```text
AttributeError: 'int' object has no attribute 'enum_name'
```

This same code worked on **pysui** `0.72.0`.

**Stack trace snippet:**

```
Traceback (most recent call last):
  ...
  File ".../lib/python3.11/site-packages/pysui/sui/sui_pgql/pgql_sync_txn.py", line 337, in transfer_sui
    return self.builder.transfer_sui(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pysui/sui/sui_txn/transaction_builder.py", line 591, in transfer_sui
    coin_arg = self.split_coin(from_coin=from_coin, amounts=[amount.value])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pysui/sui/sui_txn/transaction_builder.py", line 498, in split_coin
    amounts_arg.append(self.input_pure(amount))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pysui/sui/sui_txn/transaction_builder.py", line 305, in input_pure
    if key.enum_name == "Pure":
       ^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'enum_name'
```

## Steps to Reproduce

1. Install pysui `0.75.0` (or above)
2. Run a simple GraphQL transaction builder snippet, for example:

```python
from pysui import PysuiConfiguration, SyncGqlClient
from pysui.sui.sui_pgql.pgql_sync_txn import SuiTransaction

def test_transfer():
    config = PysuiConfiguration(
        group_name="sui_gql_config",
        profile_name="testnet",
        persist=False
    )
    client = SyncGqlClient(pysui_config=config, write_schema=False)
    txb = SuiTransaction(client=client)

    # 'amount' is a raw integer
    txb.transfer_sui(
        recipient="0x1234...",
        from_coin=txb.gas,
        amount=100_000_000  # <-- int
    )
    print("Built transaction successfully.")
    txb.build()

if __name__ == "__main__":
    test_transfer()
```

3. Observe the `AttributeError: 'int' object has no attribute 'enum_name'`.

## What I Expected

- In **pysui** `0.72.0`, passing an integer directly as `amount=100_000_000` worked. I expected the transaction to build normally.  

## Additional Context

- **Python version**: 3.11
- **pysui version**: 0.75.0  
- **Observed Behavior**: Fails with `AttributeError`  
- **Previous Behavior**: Works on 0.72.0  

**Possible cause**:  
It looks like the underlying builder now tries to access `amount.value`, or interprets the integer as a typed argument with an `enum_name` attribute. This might be a regression or new requirement to wrap `amount` in a typed object (like `SuiU64`) instead of a raw integer.

**Comment by FrankC01** [comment]
Good catch, fix will be in next release 
In meantime use split/transfer explicitly 
```python
    txb.transfer_objects(
        transfers=[txb.split_coin(coin=txb.gas, amounts=[100_000_000])],
        recipient="0x1234...",
    )
```
